version: '3.0'

services:
  php-fpm:
    # image: php:symfony
    container_name: php-fpm
    build:
      context: .
    volumes:
      - ./../:/var/www

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./../:/var/www
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites/:/etc/nginx/sites-available
      - ./conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "80:80"
      - "443:443"